- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-cj  # Delta V - Change supervisor to chief justice
  access:
  # - Service - DeltaV, removed from service department
  - Justice # DeltaV - Justice dept
  - Lawyer
  - Maintenance

- type: startingGear
  id: LawyerGear
  subGear:
    - LawyerPlasmamanGear

  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack
    back: ClothingBackpackLawyerFilled
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetSecurity
    pocket1: BookSecurity
    innerClothingSkirt: ClothingUniformJumpskirtLawyerBlack
    satchel: ClothingBackpackSatchelLawyerFilled
    duffelbag: ClothingBackpackDuffelLawyerFilled
  inhand:
    - BriefcaseBrownFilled


- type: startingGear
  id: LawyerPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitEnviroslacks
    head: ClothingHeadEnvirohelmColorWhite
    gloves: ClothingHandsGlovesEnviroglovesWhite
